baseURL = "https://seregayoga.com"
languageCode = "en-us"
title = "Sergey Fedchenko"
theme = "minimal"

[params]
    author = "Sergey Fedchenko"
    description = "software developer"
    githubUsername = "seregayoga"
    accent = "red"
    showBorder = true
    backgroundColor = "white"
    font = "Raleway" # should match the name on Google Fonts!
    highlight = true
    highlightStyle = "default"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift"]

[[menu.main]]
    url = "/"
    name = "Home"
    weight = 1

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.

[[menu.icon]]
    url = "mailto:seregayoga@gmail.com"
    name = "envelope-o"
    weight = 1

[[menu.icon]]
    url = "https://github.com/seregayoga"
    name = "github"
    weight = 2

[[menu.icon]]
    url = "https://www.linkedin.com/in/sergey-fedchenko/"
    name = "linkedin"
    weight = 4

